// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://prmnppcoeceszqrejhlr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBybW5wcGNvZWNlc3pxcmVqaGxyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU3MjMwNjIsImV4cCI6MjA5MTI5OTA2Mn0.r7kOIYLPvHmiNljTSogaWnJ2jJqK_HRmRTynk1A8WzE";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Create audits table if it doesn't existconst createAuditsTable = async () => {
  try {
    const { error } = await supabase.rpc('rpc_exec', {
      function: `
        CREATE TABLE IF NOT EXISTS audits (
          id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
          user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
          email TEXT,
          event TEXT NOT NULL,
          details JSONB,
          ip_address TEXT,
          user_agent TEXT,
          created_at TIMESTAMPTZ DEFAULT NOW()
        );
      `
    });
    
    if (error) {
      console.error('Error creating audits table:', error);
    }
    
    // Enable RLS on audits table
    const { error: rlsError } = await supabase
      .from('audits')
      .select('*')
      .limit(1);
    
    if (!rlsError) {
      // Enable RLS
      await supabase.rpc('rpc_exec', {
        function: `
          ALTER TABLE audits ENABLE ROW LEVEL SECURITY;
        `
      });
      
      // Create policy for authenticated users to read their own audits
      await supabase.rpc('rpc_exec', {
        function: `
          CREATE POLICY "Users can read own audits" 
          ON audits FOR SELECT 
          TO authenticated 
          USING (auth.uid()::text = user_id::text);
        `
      });
      
      // Create policy for admins to read all audits
      await supabase.rpc('rpc_exec', {
        function: `
          CREATE POLICY "Admins can read all audits" 
          ON audits FOR SELECT 
          TO authenticated           USING (auth.role() = 'admin');
        `
      });
    }
  } catch (error) {
    console.error('Error setting up audits table:', error);
  }
};

// Initialize audits table on client load
createAuditsTable();

export type { AuditData, AuditEvent };